# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c71b2f91-3f37-4a1f-bb3b-cd8404dc7091";
      fsType = "ext4";
    };

  fileSystems."/mnt/linux" =
  { 
    device = "/dev/nvme0n1p2";
    fsType = "ext4";
    options = [ "x-gvfs-show" "user" "exec" "auto" "nofail" ];
  };


  fileSystems."/mnt/projects" =
  { 
    device = "/dev/nvme0n1p5";
    fsType = "ext4";
    options = [ "x-gvfs-show" "user" "exec" "auto" "nofail" ];
  };

  fileSystems."/mnt/files" =
  { 
    device = "/dev/sda1";
    fsType = "ntfs";
    options = [ "x-gvfs-show" ];
  };


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1EA7-D59F";
      fsType = "vfat";
    };

  swapDevices = [ { device = "/dev/nvme0n1p3"; } ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
